################
#     Moha     #
################

# Name of your site (displayed in the header)
name: Mohamed Said Benmousa

# Short bio or description (displayed in the header)
description: Software engineer

# URL of your avatar or profile pic
avatar: https://avatars2.githubusercontent.com/u/9529785?s=400&u=a4663a82f6e8ef07d91968df9e8b3d813a008c0b&v=4

# Tabs in header.
navigation:
- name: Home
  url: /
- name: About me
  url: /about
- name: Archive
  url: /archive
- name: Tags
  url: /tags

# Pagination
paginate: 5

# Includes an icon in the footer for each username you enter
footer-links:
  email: mohamedbenmousa@gmail.com
  github: mohasaid
  linkedin: mohamed-said-benmousa
  stackoverflow: users/4713109/mohamed-said-benmousa
  rss: anything # just type anything here for a working RSS icon

# Text under the icons in footer
footer-text: © 2018 Mohamed Said Benmousa. All rights reserved.

# Disqus shortname to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: mohasaid-github-io

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-124088306-1

# Website URL
# Used for Sitemap.xml and your RSS feed
url: https://mohasaid.github.io/

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

permalink: :title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
- jekyll-feed # Create an Atom feed using the official Jekyll feed gem
- jekyll-paginate

# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
